### ISSUE TITLE
map_options loses integers in $options

### ISSUE THREAD

**Issue by jdigory** [nupfel/Web-API#24]
I'm interacting with a web service that requires JSON integers, not strings, for some things. I'm using the method documented in the JSON perl module to ensure these are integers for Perl:

`$options->{my_number} += 0;`

I am still trying to track down the cause, but when `map_options` runs over the `$options` hash, it somehow loses the numerical aspect, and the JSON payload is back to strings. Yet when I comment out the call to `map_options` in AUTOLOAD, the JSON payload uses integers.

**Comment by jdigory** [comment]
Ok, found it: when "debug" is enabled, the integers are made strings in JSON. This is somehow being done by Data::Dump's `dump`, here:

`$self->log("options:\n" . dump($options)) if $self->debug;`

If I comment that out, or remove "dump", or load Data::Dumper and use `Dumper($options)` instead, it works fine. Weird, but I think we should avoid Data::Dump because of this.

**Comment by jdigory** [comment]
Fixed in the other pull request.

**Comment by nupfel** [comment]
oh yes, the typical mistake with Data::Dump or any dumping module *sigh*. i'm sorry this happened, and very glad you found it. It's a bummer because i like the formatting of Data::Dump better. anyway i decided to go with [Data::Printer](https://metacpan.org/pod/Data::Printer) instead because i have used it in other projects before and like it a lot. i highly appreciate your pull request though and i hope you are not offended by this decision.

**Comment by jdigory** [comment]
Sure, Data::Printer sounds fine. Thanks :-)
